### ISSUE TITLE
Progresive Pach 3.0

### ISSUE THREAD

**Issue by kamila231993** [Si1ker/WotlkProgression#3]
[there](https://imageupload.io/8lxItBxeOCSzZnl) is a problem with a vendor in stormwind, you can see both the angry vendor and the savage one

<a href="https://ibb.co/0MvFKYk"><img src="https://i.ibb.co/cFVCw2P/F-r-titlu.png" alt="F-r-titlu" border="0"></a>

**Comment by kamila231993** [comment]
account no GM

**Comment by kamila231993** [comment]
this problem is only in stormwind

**Comment by kamila231993** [comment]
is there an update to the other patches 3.1 eth 3.2?

**Comment by Si1ker** [comment]
> is there an update to the other patches 3.1 eth 3.2?

Hello @kamila231993 , a deprecation note has been added to the main readme file on this repo.

The [mod-progression-system](https://github.com/azerothcore/mod-progression-system) by AzerothCore will eventually include the Wotlk content.
As of October 2023, it is up to Tier 4 of TBC content (Phase 1 of TBC Classic). I'm closing this issue and archiving this repo, thanks.
